common/models/Server.php
<?php

namespace common\models;

use Yii;


class Server extends AbstractModel {
    
    public $locate = [
        'RU' => 'RU',
        'EN' => 'EN',
        'DH' => 'DH'
    ];

    public static function tableName() {
        return 'servers';
    }

    public function getApiServers() {
        return $this->hasOne(BillingServer::className(), ['billing_id' => 'billing_id'])->alias('apiServers');
    }

    public function getLangText() {
        return $this->hasMany(LangServer::className(), ['server_id' => 'id'])
            ->where(['langText.lang' => Yii::$app->language])
            ->alias('langText');
    }

    public function getRu() {
        return $this->hasMany(LangServer::className(),  ['server_id' => 'id'])
            ->where(['ru.lang' => 'ru'])
            ->alias('ru');
    }
    public function getEn() {
        return $this->hasMany(LangServer::className(),  ['server_id' => 'id'])
            ->where(['en.lang' => 'en'])
            ->alias('en');
    }
    public function getZh() {
        return $this->hasMany(LangServer::className(),  ['server_id' => 'id'])
            ->where(['zh.lang' => 'zh'])
            ->alias('zh');
    }

    public function getAllServers($where = false, $request = true, $order = ['id' => SORT_ASC],  $lang = false) {
        $query = Server::find()
            ->joinWith('apiServers')
            ->orderBy($order)
        ->alias('servers');

        if ($lang) {
            $query->joinWith('langText');
        } else {
            $query->joinWith('ru');

        }

        if ($where) {
            $query->andWhere($where);
        }

        if ($request) {
            return $query->all();
        } else {
            return $query;
        }
    }

    public function getOneServer($where = false, $request = true, $lang = false) {
        $query = Server::find()
            ->joinWith('apiServers')
            ->alias('servers');

        if ($lang) {
            $query->joinWith('langText');
        } else {
            $query->joinWith('ru');

        }

        if ($where) {
            $query->andWhere($where);
        }

        if ($request) {
            return $query->one();
        } else {
            return $query;
        }
    }

}

common/models/VpsOs.php
<?php

namespace common\models;


class VpsOs extends AbstractModel {

    public static function tableName() {
        return 'vps_os';
    }

    public function getOs() {
        return $this->hasMany(Os::className(), ['id' => 'os_id']);
    }
    
}

backend/views/servers/edit.php
<?php
use mihaildev\ckeditor\CKEditor;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = Yii::$app->request->get('id') ? 'Редактировать' : 'Добавить';
?>
<h1><?php echo 'Серверы > ' . $this->title; ?></h1>

<?php $form = ActiveForm::begin([
    'options' => ['enctype'=>'multipart/form-data', 'class' => 'form-horizontal',],
    'fieldConfig' => [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10">{input}</div>',
        'labelOptions' => ['class' => 'col-lg-2 control-label'],
    ],
]); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->name; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'name_ru', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ru.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->ru) ? $model->ru[0]['name'] : ''])->label(); ?>
<?php echo $form->field($edit, 'name_en', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/en.jpg" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->en) ? $model->en[0]['name'] : ''])->label(); ?>
<?php echo $form->field($edit, 'name_zh', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ch.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->zh) ? $model->zh[0]['name'] : ''])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->cpuname; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'cpuname_ru', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ru.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->ru) ? $model->ru[0]['cpuname'] : ''])->label(); ?>
<?php echo $form->field($edit, 'cpuname_en', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/en.jpg" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->en) ? $model->en[0]['cpuname'] : ''])->label(); ?>
<?php echo $form->field($edit, 'cpuname_zh', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ch.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->zh) ? $model->zh[0]['cpuname'] : ''])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->ram; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'ram_ru', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ru.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->ru) ? $model->ru[0]['ram'] : ''])->label(); ?>
<?php echo $form->field($edit, 'ram_en', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/en.jpg" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->en) ? $model->en[0]['ram'] : ''])->label(); ?>
<?php echo $form->field($edit, 'ram_zh', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ch.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->zh) ? $model->zh[0]['ram'] : ''])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->hdd; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'hdd_ru', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ru.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->ru) ? $model->ru[0]['hdd'] : ''])->label(); ?>
<?php echo $form->field($edit, 'hdd_en', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/en.jpg" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->en) ? $model->en[0]['hdd'] : ''])->label(); ?>
<?php echo $form->field($edit, 'hdd_zh', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ch.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->zh) ? $model->zh[0]['hdd'] : ''])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->price; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'price')->input('text', ['value' => $model->price])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->rack; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'rack')->input('text', ['value' => $model->rack])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->chassis_templ; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'chassis_templ')->input('text', ['value' => $model->chassis_templ])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->hostname; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'hostname')->input('text', ['value' => $model->hostname])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->owner; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'owner')->input('text', ['value' => $model->owner])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->mac; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'mac')->input('text', ['value' => $model->mac])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->ip; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'ip')->input('text', ['value' => $model->ip])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->localspeed; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'localspeed_ru', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ru.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->ru) ? $model->ru[0]['localspeed'] : ''])->label(); ?>
<?php echo $form->field($edit, 'localspeed_en', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/en.jpg" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->en) ? $model->en[0]['localspeed'] : ''])->label(); ?>
<?php echo $form->field($edit, 'localspeed_zh', [
        'template' => '<label class="col-lg-2 control-label"></label>{error}{label}<div class="col-lg-10"><img class="flag" src="/images/system/ch.png" alt="russian flag">{input}</div>']
)->input('text', ['value' => !empty($model->zh) ? $model->zh[0]['localspeed'] : ''])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <p><?php echo $billingServer->os; ?></p>
    </div>
</div>
<?php echo $form->field($edit, 'os')->input('text', ['value' => $model->os])->label(); ?>
<?php echo $form->field($edit, 'location')->dropDownList($location, ['options' => [$model->location => ['selected ' => true]]])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <input type="checkbox" value="<?php echo $billingServer->raid; ?>" disabled> RAID
    </div>
</div>
<?php echo $form->field($edit, 'raid')->input('checkbox', [
    'checked' => $model->raid == 1 ? 'checked' : false,
    'class' => 'checkbox',
])->label(); ?>
<div class="form-group billing-data">
    <div class="col-lg-10 col-lg-offset-2">
        <input type="checkbox" value="<?php echo $billingServer->ipmi; ?>" disabled> IPMI
    </div>
</div>
<?php echo $form->field($edit, 'ipmi')->input('checkbox', [
    'checked' => $model->ipmi == 1 ? 'checked' : false,
    'class' => 'checkbox',
])->label(); ?>
<?php echo $form->field($edit, 'active')->input('checkbox', [
    'checked' => $model->active == 1 ? 'checked' : false,
    'class' => 'checkbox',
])->label(); ?>
<div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
        <a href="<?php echo Url::toRoute([Yii::$app->controller->id . '/index']); ?>" class="btn btn-warning">Вернуться к списку</a>
        <?php echo Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

backend/views/servers/index.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->title = 'Выделенные серверы';
?>
<h1><?php echo 'Серверы > ' . $this->title; ?></h1>
<div class="row-fluid" id="billing-update">
<!--    <a href="servers/update-servers" class="btn btn-success">Обновить список выд. серверов сейчас</a>-->
    <a class="btn btn-success update-servers">Обновить список выд. серверов сейчас</a>
</div>
<div class="row-fluid sections">
    <div class="progress progress-striped active sort-progress">
        <div class="progress-bar progress-bar-info" style="width: 100%"></div>
    </div>
    <div id="tabs">
        <ul>
            <li><a href="#list">Список серверов</a></li>
            <li><a href="#new">Новые серверы (<span id="new-count"><?php echo $countNewServers; ?></span>)</a></li>
        </ul>
        <div id="list">
            <table  class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>id</th>
                    <th>billing_id</th>
                    <th>Название</th>
                    <th>Изменён</th>
                    <th>Удалён</th>
                    <th>Активность</th>
                    <th></th>
                </tr>
                </thead>
                <?php if (!empty($allServers)) {?>
                    <?php foreach ($allServers as $server) { ?>
                        <tr>
                            <td><?php echo $server->id; ?></td>
                            <td><?php echo $server->billing_id; ?></td>
                            <td><?php echo $server->ru[0]->name; ?></td>
                            <td><?php
                                $updateBilling = new DateTime($server->apiServers->updated_at);
                                $updateServ = new DateTime($server->updated_at);
                                echo $updateBilling > $updateServ ? 'Да' : 'Нет'; ?></td>
                            <td><?php echo $server->apiServers->is_deleted ? 'Да' : 'Нет'; ?></td>
                            <td class="status"><?php echo $server->active ? 'Да' : 'Нет'; ?></td>
                            <td>
                                <div class="data col-md-12" data-id="<?php echo $server->billing_id; ?>">
                                    <div class="row">
                                        <a href="<?php echo Url::toRoute([Yii::$app->controller->id . '/edit', 'id' => $server->billing_id]); ?>" class="btn btn-default btn-xs" title="Редактировать">Edit</a>
                                        <a class="btn btn-primary btn-xs btn-activate mini" data-value="<?php echo $server->active == 1 ? 0 : 1; ?>" data-id="<?= $server->id; ?>" title="<?= $server->active ? 'Деактивировать' : 'Активировать'; ?>">
                                            <span><?php echo $server->active == 1 ? 'Deactivate' : 'Activate'; ?></span>
                                            <div class="progress progress-striped active" style="border-radius: 0;margin: 0;height: 3px; display: none">
                                                <div class="progress-bar" style="width: 100%"></div>
                                            </div>
                                        </a>
                                        <a class="btn btn-danger btn-xs btn-delete" data-id="<?= $server->id; ?>" title="Удалить">
                                            <span>Delete</span>
                                            <div class="progress progress-striped active" style="border-radius: 0;margin: 0;height: 3px; display: none">
                                                <div class="progress-bar progress-bar-danger" style="width: 100%"></div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
            </table>
            <?php if (!is_null($pagerServers)) { ?>
                <div class="row-fluid pager">
                    <?php echo LinkPager::widget([
                        'pagination' => $pagerServers,
                    ]); ?>
                </div>
            <?php } ?>
        </div>
        <div id="new">
            <table  class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Название</th>
                    <th>Владелец</th>
                    <th></th>
                </tr>
                </thead>
                <?php if (!empty($newServers)) {?>
                        <?php foreach ($newServers as $server) { ?>
                            <tr>
                                <td><?php echo $server->billing_id; ?></td>
                                <td><?php echo $server->name; ?></td>
                                <td><?php echo $server->owner; ?></td>
                                <td>
                                    <a class="btn btn-primary btn-xs btn-approve"  data-id="<?php echo $server->billing_id ?>">
                                        <span>Одобрить</span>
                                        <div class="progress progress-striped active" style="border-radius: 0;margin: 0;height: 3px; display: none">
                                            <div class="progress-bar" style="width: 100%"></div>
                                        </div>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                <?php } ?>
            </table>
            <?php if (!is_null($pagerNewServers)) { ?>
                <div class="row-fluid pager">
                    <?php echo LinkPager::widget([
                        'pagination' => $pagerNewServers,
                    ]); ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(function() {
            $( "#tabs" ).tabs();
        });
        $('.btn-approve').click(function () {
            var $this = $(this);
            var id = $this.data().id;
            $this.find('.progress').show();
            $.ajax({
                url: '<?php echo Url::to([Yii::$app->controller->id . '/approve']); ?>',
                type: 'post',
                dataType: 'json',
                data: {
                    id: id,
                    _csrf: yii.getCsrfToken()
                },
                success: function (response) {
                    if (response.status == true) {
                        $this.closest('tr').remove();
                        var newCount = parseInt($('#new-count').text()) - 1;
                        $('#new-count').text(newCount);
                    }
                    $this.find('.progress').hide();
                },
                error: function () {
                    $this.find('.progress').hide();
                }
            });
        });
        $('.update-servers').click(function () {
            var $this = $(this);
            $('.row-fluid.sections').find('.progress').show();
            $.ajax({
                url: '<?php echo Url::to([Yii::$app->controller->id . '/update-servers']); ?>',
                type: 'post',
                dataType: 'json',
                data: {
                    _csrf: yii.getCsrfToken()
                },
                success: function (response) {
                    if (response.status == true) {
                        $('.row-fluid.sections').find('.progress').hide();
                    }
                },
                error: function () {
                    $('.row-fluid.sections').find('.progress').hide();
                }
            });
        });

        $('.btn-activate').click(function () {
            var $this = $(this);
            activeAjax($this, '<?php echo Url::toRoute(Yii::$app->controller->id . '/active'); ?>', 'Activate', 'Deactivate');
        });

        $('.btn-delete').click(function () {
            var agree = confirm('Вы действительно хотите удалить этот сервер?');
            if (agree) {
                var $this = $(this);
                deleteAjax($this, '<?php echo Url::toRoute(Yii::$app->controller->id . '/delete'); ?>');
            }
        });
    });
</script>